work_dir: '.'
hydra:
    run:
        dir: ${work_dir}
seed: 1

# wandb
use_wandb: 0
wandb_project: hand_rl
wandb_group: debug
wandb_name: 0

use_bc: 1
num_demos: 50

# Environment 
env: relocate-large_clamp
from_pixels: True
hybrid_state: True
stack_frames: False
encoder_type: resnet34
encoder_ckpt: none
# ('zeroview', 'frontview', 'backview', 'sideview').
cam1: frontview 
cam2:
cam3:

episode_length: 200

# Algorithm
algorithm: DAPG

# num_cpu: 2
num_cpu: 1

save_freq: 25
eval_rollouts: 25

# BC parameters
demo_file     :   None
bc_batch_size :   32
bc_epochs     :   5
bc_learn_rate :   1e-3

# RL parameters (all params related to PG, value function, DAPG etc.)

policy_size   :   256, 256
vf_batch_size :   64
vf_epochs     :   2
vf_learn_rate :   1e-3
rl_step_size  :   0.05
rl_gamma      :   0.995
rl_gae        :   0.97
rl_num_traj   :   200
rl_num_iter   :   400
lam_0         :   1e-2
lam_1         :   0.95

output: debug


# test time adaptation
test_time_momentum: 0.01
use_encoder_adaptation: 0
adaptation_batch_size: 32
adaptation_num_iter: 1000
adaptation_lr: 1e-4
adaptation_freeze_conv: True
adaptation_init_model_path: "/home/yanjieze/projects/HandAutoencoder/archive/penn_joint.pth"
MODEL:
  NAME: 'imm_joint_model'
  PRETRAINED: 'models/pytorch/imagenet/resnet50-19c8e357.pth'
  IMAGE_SIZE:
  - 256
  - 256
  HEATMAP_SIZE:
  - 64
  - 64
  SIGMA: 2
  NUM_JOINTS: 13
  NUM_MAPS: 30
  TARGET_TYPE: 'gaussian'
  IS_IMM: true
  INIT_WEIGHTS: true
  EXTRA:
    FINAL_CONV_KERNEL: 1
    DECONV_WITH_BIAS: false
    NUM_DECONV_LAYERS: 3
    NUM_DECONV_FILTERS:
    - 256
    - 256
    - 256
    NUM_DECONV_KERNELS:
    - 4
    - 4
    - 4
    NUM_LAYERS: 50
    COMBATTN: true
    NHEADS: 4
    FFN: false
    POS_ENC: false
    TRANSFORMER: true
    NUM_TF_LAYERS: 1
    